Dialog's positive button has bigger font size now
iSoron/uhabits pull request #1096
Opened 2021-09-05 17:33 UTC by kalina559

Setting the 'OK' button size, instead of it being some default value. Fixes  #1093

2021-09-05 19:30 UTC, hiqua commented
Hey thanks for the contribution!

I'm not sure that's the right fix, since this doesn't change if you change the font size system-wide, while e.g. "change value" does change. Could you try to make it so that it just scales normally like the other text?

2021-09-05 19:49 UTC, hiqua commented
Maybe even more important before you go further with that: can you reproduce the original issue? I can't, I'll add a comment on the issue.

2021-09-05 20:35 UTC, kalina559 commented
You're totally right, now it scales along with other texts. I was able to reproduce it on Android 11

2021-09-05 21:29 UTC, hiqua requested changes

2021-09-05 21:29 UTC, hiqua commented on uhabits-android/src/main/res/values/styles.xml
> +        <item name ="android:textSize">@dimen/regularTextSize</item>
You have an extra space after `name`.

2021-09-11 12:02 UTC, iSoron commented
Thank you for the PR and welcome to the project, @kalina559. The fix looks good now.

2021-09-11 12:03 UTC, merged