Tests for DateUtils and FileExtensions
iSoron/uhabits pull request #1111
Opened 2021-09-20 04:56 UTC by sgallese

Test coverage for FileExtensions and some coverage for DateUtils
Prepare classes for migration in #1075

2021-09-22 04:45 UTC, sgallese commented
@iSoron  These tests pass, but I am a bit confused by the DateUtil implementations for:
getStartOfTodayCalendarWithOffset() ([test1](https://github.com/iSoron/uhabits/pull/1111/files#diff-364b126afb4194c42ba8ce5331c76a407f1cfaeb137327c5f1dc757043ffa29bR313 ), [test 2](https://github.com/iSoron/uhabits/pull/1111/files#diff-364b126afb4194c42ba8ce5331c76a407f1cfaeb137327c5f1dc757043ffa29bR327 )) 
getStartOfTodayWithOffset() ([test1](https://github.com/iSoron/uhabits/pull/1111/files#diff-364b126afb4194c42ba8ce5331c76a407f1cfaeb137327c5f1dc757043ffa29bR170 ), [test2](https://github.com/iSoron/uhabits/pull/1111/files#diff-364b126afb4194c42ba8ce5331c76a407f1cfaeb137327c5f1dc757043ffa29bR182)) 

For the above methods, these implementations are returning a non-offset time/calendar.
For example, if the offset is 3 hours, they still return a Midnight time/calendar.

This differs from the behavior of getStartOfTomorrowWithOffset() ([test 1](https://github.com/iSoron/uhabits/pull/1111/files#diff-364b126afb4194c42ba8ce5331c76a407f1cfaeb137327c5f1dc757043ffa29bR146), [test 2](https://github.com/iSoron/uhabits/pull/1111/files#diff-364b126afb4194c42ba8ce5331c76a407f1cfaeb137327c5f1dc757043ffa29bR158))
For example, if the offset is 3 hours, they return a 3AM time/calendar.

If this is not expected, let me know the correct expectation and I can create an issue and resolve.

2021-10-01 02:02 UTC, iSoron requested changes
Thank you for the tests, @sgallese. I think they are good. I left just some minor comments below.

2021-10-01 02:02 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/utils/DateUtilsTest.kt
> +    }
Same comment for these two tests.

2021-10-01 02:22 UTC, iSoron commented
> For the above methods, these implementations are returning a non-offset time/calendar.
> For example, if the offset is 3 hours, they still return a Midnight time/calendar.

It's also unclear to me. I suggest that we write tests for the current behavior. Changing it might introduce subtle bugs.

The underlying issue here is that, historically, we have stored all dates as milliseconds since Jan 1, 1970, but, since we don't actually care about hours/minutes/seconds in most situations, we have also implicitly assumed that most millis are a multiple of `DAY_LENGTH`. I suspect that the reason these functions are returning midnight is to keep this assumption valid. We should eventually move everything that doesn't care about hours/minutes/seconds to  `LocalDate`, which solves this ambiguity by storing time at a lower granularity.

2021-10-04 04:11 UTC, sgallese commented on uhabits-core/src/jvmMain/java/org/isoron/uhabits/core/utils/DateUtils.kt
>          }
Agreed  aae85c

2021-10-04 04:20 UTC, sgallese commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/utils/DateUtilsTest.kt
> +    }
I was able to move the first three lines to a shared helper function, but the rest of the lines are different. If I'm missing something else obvious for DRYer test code, let me know! 707b2b4

2021-10-04 05:35 UTC, sgallese commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/utils/DateUtilsTest.kt
> +    }
Actually, ended up writing much DRYer offset tests 4fbf8a8
See if these are better.
Once merged, I'll want to update the new non-JVM tests to reflect this logic in https://github.com/iSoron/uhabits/pull/1120/

2021-10-31 05:38 UTC, sgallese commented
@iSoron OK to merge this PR?

2021-11-04 01:01 UTC, merged

2021-11-04 01:01 UTC, iSoron commented
@sgallese Sorry, I missed the 'review requested' notification. It looks good now, thanks!