Issue 1332: Multiple numeric dialogs appearing
iSoron/uhabits pull request #1356
Opened 2022-04-20 21:34 UTC by kalina559

Resolves #1332.
I'm not sure about this solution though, as it's a bit of a hack. The bug itself is not that serious - users can just enter the data twice, it's not breaking the app or anything. What do you think @iSoron @hiqua ?
While working on it I also noticed that the issue appears when clicking on the tiles in ListHabitsScreen, I corrected this there as well. Numeric dialog is also shown when using a Checkmark widget, but the issue wasn't appearing there.

2022-04-21 16:43 UTC, iSoron commented
Thanks for tackling this bug, @kalina559. I agree it's not serious, but it would still be nice to fix it.

I think keeping track of the number picker visibility in `NumberPickerFactory` is problematic. For example, if, for any reason, `onDismissListener` does not get called, we would get stuck in a state where the number picker can no longer be shown until the app is restarted.

I would suggest the following instead. Whoever calls `NumberPickerFactory(...).create` should keep a reference to the dialog, and should dismiss it before showing a new one. Something like this:

```
if (currentPicker != null) currentPicker.dismiss()
currentPicker = NumberPickerFactory(this@ShowHabitActivity).create(value, unit, notes, dateString, frequency, callback)
currentPicker.show()
```

2022-04-21 18:49 UTC, kalina559 commented
I made something between the initial solution and the one you described - we're keeping a reference in a companion object of 
`NumberPickerFactory` and we dismiss it when create() is called to create a new dialog. This way we avoid writing almost identical code in both `ListHabitsScreen `and `ShowHabitActivity`.

The only downside to that is that users can see the first dialog for a split second before it gets dismissed. In the first solution the second dialog was prevented from being created if another one already existed, so the UX was a bit better.

2022-04-21 23:36 UTC, iSoron requested changes
Thanks, that also works. I only have one comment below. Other than that, the PR looks fine to me.

2022-04-21 23:36 UTC, iSoron commented on uhabits-android/src/main/java/org/isoron/uhabits/activities/habits/show/ShowHabitActivity.kt
> +            ).show()
These changes look unnecessary. Could you please revert them?

2022-05-01 21:23 UTC, kalina559 commented
Hey @iSoron, can I merge this?

2022-05-02 01:01 UTC, merged

2022-05-02 01:01 UTC, iSoron commented
@kalina559 I've merged it, thanks!