Use dark theme in settings window.
iSoron/uhabits pull request #655
Opened 2020-11-11 22:41 UTC by Sunxy88

#545  Add 4 lines of code referred to [EditHabitActivity.kt](android/uhabits-android/src/main/java/org/isoron/uhabits/activities/habits/edit/EditHabitActivity.kt) to apply dark theme in settings window.

2020-11-13 12:37 UTC, iSoron requested changes
Thank you for the pull request, @Sunxy88. I have tested it and it works great. I only have one comment about code style. After that is fixed, I can merge it.

2020-11-13 12:37 UTC, iSoron commented on android/uhabits-android/src/main/java/org/isoron/uhabits/activities/settings/SettingsActivity.java
> +import org.isoron.uhabits.HabitsApplication;
Please use wildcard imports

2020-11-14 13:56 UTC, iSoron approved these changes

2020-11-14 13:57 UTC, merged

2020-11-14 13:58 UTC, iSoron commented
Looks great now. Thanks again, @Sunxy88!

2020-11-27 00:18 UTC, szpak commented
Unfortunately, it doesn't work for me with 1.8.9 and 1.8.10 from Google Play. Dark theme enabled, but the settings panel is as white as it was before. I forced the app to restart. Android 11.

2020-11-27 00:22 UTC, iSoron commented
@szpak This fix will become available in Loop 2.0

2020-11-27 19:54 UTC, szpak commented
@iSoron Thanks for your explanation, I've just taken a brief look into default branch (dev), not spotting that 1.8.x is from master.