Kotlin Conversions
iSoron/uhabits pull request #709
Opened 2021-01-14 14:35 UTC by hiqua

2021-01-16 14:06 UTC, iSoron requested changes
Thank you for the pull request, @hiqua. This is great!

I have reviewed about half of the files; I will review the remaining ones soon.

2021-01-16 14:06 UTC, iSoron commented on uhabits-android/src/main/java/org/isoron/uhabits/widgets/views/EmptyWidgetView.kt
> +    private var title: TextView? = null
Please make this `lateinit var` instead

2021-01-16 14:06 UTC, iSoron commented on uhabits-android/src/main/java/org/isoron/uhabits/widgets/views/GraphWidgetView.kt
> +    private var title: TextView? = null
Please make this `lateinit var` instead

2021-01-17 15:34 UTC, hiqua commented
Ready for a second review. I'll merge the fixing commits with the corresponding others once we're through.

2021-01-17 21:54 UTC, iSoron requested changes

2021-01-17 21:54 UTC, iSoron commented on uhabits-android/src/androidTest/java/org/isoron/uhabits/acceptance/AboutTest.kt
> +        ListHabitsSteps.clickMenu(ListHabitsSteps.MenuItem.ABOUT)
Could you static import this method too?

2021-01-17 21:54 UTC, iSoron commented on uhabits-android/src/androidTest/java/org/isoron/uhabits/acceptance/HabitsTest.kt
> +        CommonSteps.pressBack()
Could you static-import this method?

2021-01-17 21:54 UTC, iSoron commented on uhabits-android/src/androidTest/java/org/isoron/uhabits/acceptance/LinksTest.kt
> +        ListHabitsSteps.clickMenu(ListHabitsSteps.MenuItem.ABOUT)
Could you static-import this method?

2021-01-17 21:54 UTC, iSoron commented on uhabits-android/src/main/java/org/isoron/uhabits/activities/habits/list/ListHabitsRootView.kt
> +        header.setMaxDataOffset(kotlin.math.max(MAX_CHECKMARK_COUNT - count, 0))
Could you static-import `max` and `min`?

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/BaseUnitTest.kt
> +    protected open var commandRunner: CommandRunner? = null
I think the majority of these are initialized in `setUp`, so they could be `lateinit var` instead

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/BaseUnitTest.kt
> +        cal[year, month, day, 0, 0] = 0
It seems like the automatic Kotlin conversion transforms `cal.set(year, month, day, hour, min, sec)` into `cal[year, month, day, hour, min] = sec`. Could you correct this?

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/BaseUnitTest.kt
> +        cal[year, month, day, hour] = minute
Same here

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/BaseUnitTest.kt
> +        throw IllegalStateException("asset not found: $fullPath")
Could you rename `in` so we don't need backticks?

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/commands/ChangeHabitColorCommandTest.kt
> +        for ((color) in selected!!) MatcherAssert.assertThat(
Please replace `(color) in selected!!` by `habit in selected!!`, and then `color` by `habit.color`.

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/commands/ChangeHabitColorCommandTest.kt
> +        for ((color) in selected!!) MatcherAssert.assertThat(
Same here

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/commands/CreateHabitCommandTest.kt
> +        val (_, _, _, _, _, name) = habitList!!.getByPosition(0)
Please replace this by `val habit = habitList!!.getByPosition(0)`

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/commands/EditHabitCommandTest.kt
> +    private var today: Timestamp? = null
Please replace these by `lateinit var`

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/commands/EditHabitCommandTest.kt
> +        MatcherAssert.assertThat(habit!!.name, Matchers.equalTo("original"))
Could you static-import `assertThat` and `equalTo`?

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/commands/UnarchiveHabitsCommandTest.kt
> +        Assert.assertFalse(habit.isArchived)
Please static-import `assert` methods

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/database/migrations/Version22Test.kt
> +    private var helper: MigrationHelper? = null
Please replace by `lateinit var`

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/io/HabitsCSVExporterTest.kt
> +        Assert.assertNotNull(baseDir)
Please static-import assert methods

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/io/HabitsCSVExporterTest.kt
> +    //    }
Please delete this. Also, feel free to delete any other commented-out tests.

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/io/ImportTest.kt
> +        TestCase.assertFalse(isChecked(habit, 2016, 3, 17))
Please static-import assert methods

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/io/ImportTest.kt
> +        date[year, month - 1] = day
Please replace this by `date.set(year, month-1, day)`

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/models/HabitListTest.kt
> +    private var reminderHabits: HabitList? = null
Please replace by `lateinit var`

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/models/HabitListTest.kt
> +        MatcherAssert.assertThat(reminderHabits!!.size(), CoreMatchers.equalTo(4))
Please use static imports in `assertThat` and `equalTo`. Same for the other usages in this file.

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/models/HabitListTest.kt
> +        h1.position = 1
Could you use `apply` to make this look nicer?
```kotlin
val h1 = fixtures.createEmptyHabit().apply {
    name = "A Habit"
    color = [...]
}
```
An alternative would be making `name`, `color`, `position` etc arguments of `createEmptyHabit`, but provide default values.

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/models/HabitListTest.kt
> +        list.add(h2)
`apply` could also be used here

2021-01-17 21:54 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/models/HabitListTest.kt
> +                val (_, _, _, id, _, _, position) = habitList!!.getByPosition(j)
Please change to `val habit = habitList!!.getByPosition(j)`

2021-01-19 02:06 UTC, iSoron requested changes
Just a few minor changes requested. Hopefully we can merge it after these are fixed.

2021-01-19 02:06 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/models/HabitListTest.kt
> +        )
Please put these in a single line. I think ktlint breaks lines, but doesn't merge them back.

2021-01-19 02:06 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/ui/screens/habits/list/ListHabitsMenuBehaviorTest.kt
> +        )
I think these could be in a single line. There are many other similar cases in this file.

2021-01-19 02:06 UTC, iSoron commented on uhabits-core/src/jvmTest/java/org/isoron/uhabits/core/utils/DateUtilsTest.kt
> +        assertThat(truncate(field, t2, firstWeekday), CoreMatchers.equalTo(expected))
Please use static imports

2021-01-19 13:24 UTC, hiqua commented
I've removed the assertNonNull and replaced them with `!!`. These are bound to disappear completely anyway, once we've got rid of (most of) the nullable types in kotlin.

2021-01-19 21:01 UTC, hiqua commented
@iSoron can you update https://github.com/iSoron/uhabits/issues/685 once we're done with this PR?

2021-01-21 12:23 UTC, iSoron approved these changes

2021-01-21 12:24 UTC, merged

2021-01-21 12:24 UTC, iSoron commented
Merged! Thanks for this PR, @hiqua. I'm sure it was a lot of work. I'll update #685 soon.